server:
  port: 80


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC
      username: root
      password: 123456
  devtools:
    restart:
      # 不参与热部署的文件，或者文件夹
      exclude: static/**, public/**, config/application.yml
      # 热部署是否可用
      enabled: false

mybatis-plus:
  global-config:
    db-config:
      # 设置文件输出的前缀
      table-prefix: tb_
      id-type: auto
  configuration:
    # 设置mybatis-plus是否输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
